package main

// SQLServerFieldType SQLServer字段类型长度精度的描述
var SQLServerFieldType = map[string]FieldType{
	"BIGINT":           {false, false},
	"BINARY":           {true, false},
	"BIT":              {false, false},
	"CHAR":             {true, false},
	"DATE":             {false, false},
	"DATETIME":         {false, false},
	"DATETIME2":        {true, false},
	"DATETIMEOFFSET":   {true, false},
	"DECIMAL":          {true, true},
	"DOUBLE PRECISION": {false, false},
	"FLOAT":            {true, false},
	"IMAGE":            {false, false},
	"INT":              {false, false},
	"INTEGER":          {false, false},
	"MONEY":            {true, true},
	"NCHAR":            {true, false},
	"NTEXT":            {false, false},
	"NUMERIC":          {true, true},
	"NVARCHAR":         {true, false},
	"REAL":             {false, false},
	"ROWVERSION":       {false, false},
	"SMALLDATETIME":    {false, false},
	"SMALLINT":         {false, false},
	"SMALLMONEY":       {false, false},
	"TEXT":             {false, false},
	"TIME":             {true, false},
	"TIMESTAMP":        {false, false},
	"TINYINT":          {false, false},
	"UNIQUEIDENTIFIER": {false, false},
	"VARBINARY":        {true, false},
	"VARCHAR":          {true, false},
	"XML":              {false, false},
}
