package main

// OracleFieldType Oracle字段类型长度精度的描述
var OracleFieldType = map[string]FieldType{
	"BFILE":                          {false, false},
	"BINARY_FLOAT":                   {false, false},
	"BINARY_DOUBLE":                  {false, false},
	"BLOB":                           {false, false},
	"CHAR":                           {true, false},
	"CHARACTER":                      {true, false},
	"CLOB":                           {false, false},
	"DATE":                           {false, false},
	"DECIMAL":                        {true, true},
	"DOUBLE PRECISION":               {false, false},
	"FLOAT":                          {false, false},
	"INTEGER":                        {false, false},
	"INT":                            {false, false},
	"INTERVAL YEAR TO MONTH":         {false, false},
	"INTERVAL DAY TO SECOND":         {false, false},
	"LONG":                           {false, false},
	"LONG RAW":                       {false, false},
	"NCHAR":                          {true, false},
	"NCHAR VARYING":                  {true, false},
	"NCLOB":                          {false, false},
	"NUMBER":                         {false, false},
	"NUMERIC":                        {true, true},
	"NVARCHAR2":                      {true, false},
	"RAW":                            {true, false},
	"REAL":                           {false, false},
	"ROWID":                          {false, false},
	"SMALLINT":                       {false, false},
	"TIMESTAMP":                      {true, false},
	"TIMESTAMP WITH LOCAL TIME ZONE": {true, false},
	"TIMESTAMP WITH TIME ZONE":       {true, false},
	"UROWID":                         {true, false},
	"VARCHAR":                        {true, false},
	"VARCHAR2":                       {true, false},
	"XMLTYPE":                        {false, false},
}
